---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: physics-cr-sa
  namespace: physics-cluster-registration
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: physics-cr-role
  namespace: physics-cluster-registration
rules:
- apiGroups: ["cluster.open-cluster-management.io/v1"]
  resources:
  - managedclusters
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: physics-cr-rolebinding
  namespace: physics-clusters-registration
roleRef:
  apiGroup: rback.authorization.k8s.io
  kind: Role
  name: physics-cr-role
subjects:
- kind: ServiceAccount
  name: physics-cr-sa
  namespace: physics-cluster-registration
