apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    app.openshift.io/route-disabled: 'true'
  name: cluster-registration
  namespace: physics-cluster-registration
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '1'
        autoscaling.knative.dev/minScale: '1'
    spec:
      containerConcurrency: 1
      serviceAccountName: physics-cr-sa
      containers:
        - image: >-
          # change image by the real service sync
          # image: gcr.io/knative-releases/knative.dev/eventing/cmd/event_display
          image: quay.io/ltomasbo/cluster-registration:latest
          imagePullPolicy: Always
          name: cluster-registration
          ports:
            - containerPort: 8080
              protocol: TCP
